In [15]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [3]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
# Preprocessing the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
# Encode categorical features
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
# Onehot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [7]:
# combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis = 1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [8]:
#Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
# Split into train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaler these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [11]:
X_train, y_train

(array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
         -0.57946723, -0.57638802],
        [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
          1.72572313, -0.57638802],
        [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
         -0.57946723,  1.73494238],
        ...,
        [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
         -0.57946723, -0.57638802],
        [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
         -0.57946723, -0.57638802],
        [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
          1.72572313, -0.57638802]], shape=(8000, 12)),
 9254    179093.26
 1561    195978.86
 1670     85891.02
 6087    153080.40
 6669     39488.04
           ...
 5734     69381.05
 5191       706.50
 5390     92220.12
 860      97508.04
 7270     53581.14
 Name: EstimatedSalary, Length: 8000, dtype: float64)

In [14]:
# Save the encoders and scaler for later use
with open('label_encoder_gender_for_regression.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo_for_regression.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler_for_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regression Problem statement

In [16]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression
])

c:\Users\aksha\Documents\github\ML_learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
# Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#set up tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir= log_dir, histogram_freq=1)

In [20]:
# Set up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [21]:
#Train the model
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 100340.4766 - mae: 100340.4766 - val_loss: 98388.1719 - val_mae: 98388.1719
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 99188.3984 - mae: 99188.3984 - val_loss: 96120.9609 - val_mae: 96120.9609
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 95300.5391 - mae: 95300.5391 - val_loss: 90535.6719 - val_mae: 90535.6719
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88001.4844 - mae: 88001.4844 - val_loss: 81785.2578 - val_mae: 81785.2578
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 78151.8828 - mae: 78151.8828 - val_loss: 71564.2188 - val_mae: 71564.2188
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 67871.1094 - mae: 67871.1094 - val_loss: 62339.3789 - val_mae: 62339.3789
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59503.9492 - mae: 59503.9492 - val_loss: 55831.2539 - val_mae: 55831.2539
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54198.5195 - mae: 54198.5195 - val_loss: 52336.4414 - val_mae: 52336.4414
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51683.2109 - mae: 51683.2109 - val_loss: 51009.9414 - val_mae: 51009.9414
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50704.2969 - mae: 50704.2969 - val_loss: 50620.2969 - val_mae: 50620.2969
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50353.2266 - mae: 50353.2266 - val_loss: 50519.8906 - val_mae: 50519.8906
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50222.4258 - mae: 50222.4258 - val_loss: 50479.9023 - val_mae: 50479.9023
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50146.2930 - mae: 50146.2930 - val_loss: 50440.8047 - val_mae: 50440.8047
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50091.7031 - mae: 50091.7031 - val_loss: 50398.5430 - val_mae: 50398.5430
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50046.6055 - mae: 50046.6055 - val_loss: 50368.8125 - val_mae: 50368.8125
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50000.9375 - mae: 50000.9375 - val_loss: 50341.2891 - val_mae: 50341.2891
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49966.0078 - mae: 49966.0078 - val_loss: 50318.0859 - val_mae: 50318.0859
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49935.5117 - mae: 49935.5117 - val_loss: 50309.3398 - val_mae: 50309.3398
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49903.8477 - mae: 49903.8477 - val_loss: 50293.8164 - val_mae: 50293.8164
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49874.5703 - mae: 49874.5703 - val_loss: 50280.8984 - val_mae: 50280.8984
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49850.5312 - mae: 49850.5312 - val_loss: 50262.6719 - val_mae: 50262.6719
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 49825.1758 - mae: 49825.1758 - val_loss: 50249.5859 - val_mae: 50249.5859
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49802.4023 - mae: 49802.4023 - val_loss: 50240.7852 - val_mae: 50240.7852
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49781.0391 - mae: 49781.0391 - val_loss: 50230.3945 - val_mae: 50230.3945
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49758.7969 - mae: 49758.7969 - val_loss: 50227.7305 - val_mae: 50227.7305
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49737.3984 - mae: 49737.3984 - val_loss: 50213.8867 - val_mae: 50213.8867
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49720.9414 - mae: 49720.9414 - val_loss: 50210.8555 - val_mae: 50210.8555
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49704.4453 - mae: 49704.4453 - val_loss: 50201.5469 - val_mae: 50201.5469
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49686.4688 - mae: 49686.4688 - val_loss: 50205.1953 - val_mae: 50205.1953
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49673.0117 - mae: 49673.0117 - val_loss: 50204.0859 - val_mae: 50204.0859
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49654.4609 - mae: 49654.4609 - val_loss: 50208.1914 - val_mae: 50208.1914
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49637.3242 - mae: 49637.3242 - val_loss: 50199.4492 - val_mae: 50199.4492
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49625.5273 - mae: 49625.5273 - val_loss: 50200.3711 - val_mae: 50200.3711
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49613.7578 - mae: 49613.7578 - val_loss: 50202.0859 - val_mae: 50202.0859
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49598.7656 - mae: 49598.7656 - val_loss: 50200.8984 - val_mae: 50200.8984
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49590.5703 - mae: 49590.5703 - val_loss: 50198.0898 - val_mae: 50198.0898
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49575.4609 - mae: 49575.4609 - val_loss: 50191.1836 - val_mae: 50191.1836
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49563.8125 - mae: 49563.8125 - val_loss: 50197.3750 - val_mae: 50197.3750
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49558.3281 - mae: 49558.3281 - val_loss: 50205.8789 - val_mae: 50205.8789
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49547.7188 - mae: 49547.7188 - val_loss: 50201.1797 - val_mae: 50201.1797
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49536.0117 - mae: 49536.0117 - val_loss: 50205.1914 - val_mae: 50205.1914
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49528.8906 - mae: 49528.8906 - val_loss: 50206.0703 - val_mae: 50206.0703
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49518.1953 - mae: 49518.1953 - val_loss: 50194.0938 - val_mae: 50194.0938
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49511.9570 - mae: 49511.9570 - val_loss: 50191.4102 - val_mae: 50191.4102
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49505.5781 - mae: 49505.5781 - val_loss: 50205.7461 - val_mae: 50205.7461
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49496.4375 - mae: 49496.4375 - val_loss: 50221.3203 - val_mae: 50221.3203
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49488.5938 - mae: 49488.5938 - val_loss: 50217.7305 - val_mae: 50217.7305

In [28]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [29]:
%tensorboard --logdir regressionlogs/fit/fits

Reusing TensorBoard on port 6006 (pid 10088), started 0:04:36 ago. (Use '!kill 10088' to kill it.)

In [30]:
# Evaluate model on test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50191.1836 - mae: 50191.1836
Test MAE: 50191.18359375

In [31]:
model.save('regression_model.keras')